### ISSUE TITLE
Pencil icon drawn in wrong position on Alcatel Pixi 4

### ISSUE THREAD

**Issue by martinburchell** [RudolfCardinal/camcops#130]
Client 2.4.1
![Screenshot_20210211-105942](https://user-images.githubusercontent.com/192929/107628400-7ae9da00-6c58-11eb-8f0e-11e994869f7a.png)

**Comment by RudolfCardinal** [comment]
This bug, I think: https://bugreports.qt.io/browse/QTBUG-58503

**Comment by martinburchell** [comment]
Oh right yes. I see your comment from four years ago.So will be fixed if/when we move to Qt 6.0.

**Comment by martinburchell** [comment]
Worked around by #134 so closing for now.
