### ISSUE TITLE
New group member permission to add patients

### ISSUE THREAD

**Issue by martinburchell** [RudolfCardinal/camcops#159]
Currently only the group administrator can add patients on the server. It would be useful for other members of the group to be able to add patients.

**Comment by RudolfCardinal** [comment]
Yes. Do you think this merits a specific permission flag?

**Comment by martinburchell** [comment]
> Yes. Do you think this merits a specific permission flag?

@RudolfCardinal I was thinking yes and happy to hear other ideas

**Comment by RudolfCardinal** [comment]
I agree -- in that it would clearly be useful for research study members to be able to add patients (with checks that they are not adding duplicates), but not everybody would need or should have such an authorization. I'd envisage it being part of the user-group association as with most. The functional permission would be "this flag set or group administrator or superuser". It would be less clear to merge it with the "can upload?" flag. I'm not sure that permission to edit schedules is the same thing, though -- did you envisage group administrators being the only ones to edit schedules?

**Comment by martinburchell** [comment]
> I'm not sure that permission to edit schedules is the same thing, though -- did you envisage group administrators being the only ones to edit schedules?

@RudolfCardinal at this point yes. I'm assuming that patients will be added far more frequently than the schedules change.
