### ISSUE TITLE
Bad 'filename' parameter: Invalid string. Permitted characters: A-Z, a-z, 0-9, '_'  when downloading file

### ISSUE THREAD

**Issue by martinburchell** [RudolfCardinal/camcops#178]
It is not possible to download a file from the download area:

This fails because it contains `-` and `.` characters: 

`/download_file?filename=CamCOPS_dump_2021-06-04T100622.zip`

**Comment by RudolfCardinal** [comment]
Fix in https://github.com/RudolfCardinal/camcops/pull/179
