### ISSUE TITLE
Behaviour of count_where in cc_task.py is different to countWhere in mathfunc.cpp for null values 

### ISSUE THREAD

**Issue by martinburchell** [RudolfCardinal/camcops#18]
It looks like the C++ version of `countWhere` will count null values as zero where as the Python `count_where` does not.

I hit this with the SHAPS task. Compare https://github.com/RudolfCardinal/camcops/blob/shaps-dev/server/camcops_server/tasks/shaps.py#L128 and https://github.com/RudolfCardinal/camcops/blob/shaps-dev/tablet_qt/tasks/shaps.cpp#L114

If I don't have the completion check and there are null fields, the results will be different.

In this case it probably isn't helpful to give a partial score when the questionnaire is incomplete.

**Comment by RudolfCardinal** [comment]
Good spot! I think this bug only manifests here. Have fixed mathfunc::countWhere() and mathfunc::countWhereNot() to be NULL-aware, via mathfunc::containsRespectingNull(). The problem was that QVector::contains() ignores NULL status and just uses operator==().
