### ISSUE TITLE
Artefacts on Windows client (VS 2019 bug?)

### ISSUE THREAD

**Issue by martinburchell** [RudolfCardinal/camcops#37]
![image](https://user-images.githubusercontent.com/192929/65320107-0b71d700-db99-11e9-8953-9421495d7cc4.png)

**Comment by martinburchell** [comment]
![image](https://user-images.githubusercontent.com/192929/65320227-4d028200-db99-11e9-8175-96695ce7a193.png)

**Comment by martinburchell** [comment]
See https://github.com/qtwebkit/qtwebkit/issues/815 and https://bugreports.qt.io/browse/QTBUG-75280

**Comment by martinburchell** [comment]
@RudolfCardinal The suggestion in the qtwebkit issue is to add "-T \v141" to the cmake args. Where do we do that?

**Comment by RudolfCardinal** [comment]
We call ``VCVARSALL.BAT`` from ``build_qt.py`` to get the environment (see ``def _set_windows_env(...)`` and especially ``args = [VCVARSALL, arch]``). That's what determines which compiler is found and where, I think. That batch file recognizes ``--vcvars_ver`` or ``-vcvars_ver`` or ``/vcvars_ver``; see the batch file and https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=vs-2019. So the answer might be that if VS2019 is in use, to pass extra arguments via ``if using_duff_compiler: args += ["--vcvars_ver", "14.16"]`` or similar. Haven't tried it yet. The syntax would need a careful check; glancing at ``vcvarsall.bat`` from VS2017 Community (in ``C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build``) makes it look like you need ``--vcvars_ver 14.16`` but the Microsoft link above suggests ``--vcvars_ver=14.16``; perhaps they changed the syntax...

**Comment by martinburchell** [comment]
This is fixed in the latest release of Visual Studio so nothing for us to do
