### ISSUE TITLE
ODS export produces very large files

### ISSUE THREAD

**Issue by martinburchell** [RudolfCardinal/camcops#56]
Exporting tasks to ODS produces very large files because no zip compression is being applied.

A later commit in odswriter addresses this, https://github.com/mmulqueen/odswriter/commit/dfd16de720ff2e9cd4f8df4eda2d52c6fe77050a but there hasn't been a release with this change. ODSWriter itself hasn't been updated itself for over three years.

It would probably be safe to pin odswriter to this commit or we might want to look into alternatives.

**Comment by RudolfCardinal** [comment]
OK. Worth looking at others? I see there is https://github.com/pyexcel/pyexcel-ods3 = https://pypi.org/project/pyexcel-ods3/ , and https://github.com/pyexcel/pyexcel = https://pypi.org/project/pyexcel/ . Not sure of the differences between those. (I guess that since XLSX is an open standard, this is perhaps not critical, but nice.)

**Comment by martinburchell** [comment]
> OK. Worth looking at others? I see there is https://github.com/pyexcel/pyexcel-ods3 = https://pypi.org/project/pyexcel-ods3/ , and https://github.com/pyexcel/pyexcel = https://pypi.org/project/pyexcel/ . Not sure of the differences between those. (I guess that since XLSX is an open standard, this is perhaps not critical, but nice.)

It looks like pyexcel-ods and pyexcel-ods3 are both plugins for pyexcel, Each uses a different underlying library. It looks like we rejected pyexcel-ods3 earlier in the year https://github.com/RudolfCardinal/camcops/blob/master/server/camcops_server/cc_modules/cc_tsv.py#L50

**Comment by RudolfCardinal** [comment]
Hmm. Maybe I was unimpressed stylistically. However, it is faster and much smaller. Standardized large demo spreadsheet benchmarked (see cc_tsv.py):

- TSV ZIP: about 4.1 Mb, about 0.2 s. Good.
- XLSX (via openpyxl): about 4.6 Mb, 16 seconds.
- XLSX (via pyexcel_xlsx): about 4.6 Mb, 16 seconds.
- ODS (via odswriter): about 53 Mb, 56 seconds.
- ODS (via pyexcel_ods3): about 2.8 Mb, 29 seconds.

Have switched. In the process rediscovered that it requires more manual type conversion. See what you think.

**Comment by martinburchell** [comment]
@RudolfCardinal looks good. I'm wondering if we should apply some compression to TSV ZIP (default is ZIP_STORED which is uncompressed). Presumably this will increase the time to serve file.

**Comment by RudolfCardinal** [comment]
Ah! Oops. Yes, I think a good idea to compress.

**Comment by RudolfCardinal** [comment]
Implemented (in master) with Deflate compression.
